language: python
matrix:
  include:
  - python: 2.6
    env: TOXENV=py26
  - python: 2.7
    env: TOXENV=py27
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
dist: trusty
install:
- pip install tox
script: tox
env:
  global:
    secure: Yy46nbBh/YPhqFsk1iWVPQOrVC+K/jG2ZxY1QsGKMJs5BaKaOzXipnZA8oYGG2IJe5cMtisBMcIVN3SbPAtvtatBMbf+pB96JJogOxRtaNtw4NJosozQquY6e0gH8Igrjhikar8DLPR6ZrAaF9iY9+EZeZLu/7Yvw4Y8B5wuEdll1D+vJphI/gw+zbm+rfd4V+pvYq87ZdDJijBZRuURYs7LdrGYUDcCCVMifD4mUgyqVDTPnnmt7ZGMStUCMDzp0e9knGSzbYMNV/Pj9CgTlLtNUNrQ89rUTqUbfyAummAI6go7SjrQ9k5gd5mx6GXg6Dj2U/hk9bqIt//qykzIKOZXSSm5zWyCbnQte/ixO42OfhOI4gRsTFr/nqoLgusWrwz+sHQ2GvdtUY9dBoRlT416ZyMC1NVn2/yUBQyLOPWopXTHLhRRDrRcnqrPXacklLd2v/m9tceW/buhJw4dHyszv3wkVwo0AhH+GS+t2BFULIrXXbc9EbUy3pMDQpLg5qNXnjketlHUMPTu38FN24cJgBo+ZZW32viOFjZVG1JmwLi+haEKthoorGKpUwLL+Ml1Q0loyoTLbvSWEHC34KPWLPzZn9EeYycC6ms7M+TI9fafVlESS4NFw500Nh/NAd0iiEa64EAtnkUOU37+Wr1/o1S1WAbM919bEQzS1Nk=
